### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by msiebuhr** [unexpectedjs/unexpected-moment#4]
I'd really love to use the new assertions (and other upgrades) here.

Mind cutting a release?

**Comment by joelmukuthu** [comment]
Certainly, sorry for the delay. I've published it as v2.0.0 on npm.

**Comment by joelmukuthu** [comment]
Btw that was published from master. I'm really looking forward to merging https://github.com/unexpectedjs/unexpected-moment/pull/3 but it's still a work in progress. If you have some time and would like to have a look, your opinion on the outstanding issues would be greatly appreciated :)
